export const FETCH_TRANSACTION_QUERY_KEY = "FETCH_TRANSACTION_QUERY_KEY";

export const FETCH_ASSET_TRANSACTION_QUERY_KEY =
  "FETCH_ASSET_TRANSACTION_QUERY_KEY";

export const FETCH_OVERALL_STAT_QUERY_KEY = "FETCH_OVERALL_STAT_QUERY_KEY";

export const FETCH_ASSET_QUERY_KEY = "FETCH_ASSET_QUERY_KEY";
