// Stats
export const FETCH_STOCK_OVERALL_STATS = "FETCH_STOCK_OVERALL_STATS";

// Stock
export const FETCH_ALL_STOCK = "FETCH_ALL_STOCK";

// Stock Transaction
export const FETCH_ALL_STOCK_TRANSACTION = "FETCH_ALL_STOCK_TRANSACTION";
export const FETCH_ALL_STOCK_HOLDING = "FETCH_ALL_STOCK_HOLDING";
export const FETCH_ALL_STOCK_PROFIT_LOSS = "FETCH_ALL_STOCK_PROFIT_LOSS";
export const ADD_STOCK_TRANSACTION = "ADD_STOCK_TRANSACTION";
