import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";

// Global CSS
import "@/styles/globals.css";

// Lib
import { cn } from "@/lib/utils";

// Providers
import { AuthProvider } from "@/providers/auth/AuthProvider";
import { ThemeProvider } from "@/providers/theme-provider/ThemeProvider";
import { ReactQueryProvider } from "@/providers/react-query/ReactQueryProvider";

// Components
import { Navbar } from "@/components/layout/Navbar";

// Font
const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn("bg-background font-sans antialiased", ubuntu.className)}
      >
        <AuthProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <ReactQueryProvider>
              <Navbar />
              <main className="relative isolate w-full h-full px-6 pt-32 pb-10 lg:px-8">
                {children}
              </main>
            </ReactQueryProvider>
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
