import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";

// Global CSS
import "@/styles/globals.css";

// Lib
import { cn } from "@/lib/utils";

// Providers
import { AuthProvider } from "@/providers/auth/AuthProvider";
import { ThemeProvider } from "@/providers/theme-provider/ThemeProvider";
import { ReactQueryProvider } from "@/providers/react-query/ReactQueryProvider";

// Components
import { Navbar } from "@/components/layout";

// Font
const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn("bg-background antialiased h-full", ubuntu.className)}
      >
        <AuthProvider>
          <ReactQueryProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <Navbar />
              <main className="relative isolate px-3 pt-32 pb-10 lg:px-8">
                {children}
              </main>
            </ThemeProvider>
          </ReactQueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
